- hosts: all
  become: yes
  tasks:
  - name: Remove swapfile from /etc/fstab
    mount:
      name: swap
      fstype: swap
      state: absent

  - name: Disable swap
    command: swapoff -a
    when: ansible_swaptotal_mb > 0

  - name: create the 'mulugeta' user
    user: name=mulugeta append=yes state=present createhome=yes shell=/bin/bash

  - name: allow 'mulugeta' to have passwordless sudo
    lineinfile:
      dest: /etc/sudoers
      line: 'mulugeta ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'

  - name: set up authorized keys for the mulugeta user
    authorized_key: user=mulugeta key="{{item}}"
    with_file:
      - ~/.ssh/id_rsa.pub

  - name: Assign inventory name to unconfigured hostnames (non-CoreOS, Suse and ClearLinux)
    hostname:
      name: "{{ inventory_hostname }}"

  - name: "Add IP address of all hosts to all hosts"
    lineinfile:
      dest: /etc/hosts
      regexp: '.*{{ item }}$'
      line: "{{ hostvars[item].ansible_host }} {{item}}"
      state: present
    when: hostvars[item].ansible_host is defined
    with_items: "{{ groups.all }}"

  - name: install remote apt deps
    apt:
     name: "{{ item }}"
     state: present
    with_items:
     - apt-transport-https
     - ca-certificates
     - gnupg2
     - software-properties-common

  - name: add Docker apt-key
    apt_key:
     url: https://download.docker.com/linux/debian/gpg
     state: present

  - name: add Docker's APT repository
    apt_repository:
     repo: deb https://download.docker.com/linux/debian stretch stable
     state: present
     filename: 'docker'

  - name: install Docker
    apt:
     name: docker-ce
     state: present
     update_cache: true

  - name: add Kubernetes apt-key
    apt_key:
     url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
     state: present

  - name: add Kubernetes' APT repository
    apt_repository:
     repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
     state: present
     filename: 'kubernetes'

  - name: install kubelet
    apt:
     name: kubelet=1.14.0-00
     state: present
     update_cache: true

  - name: install kubeadm
    apt:
     name: kubeadm=1.14.0-00
     state: present
